# Generated by Django 2.2.3 on 2019-07-19 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('pass_word', models.CharField(max_length=200)),
                ('create_date', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
