# Generated by Django 2.2.3 on 2019-07-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userentity',
            table='user',
        ),
    ]
