# Generated by Django 2.2.3 on 2019-09-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_type', '0004_auto_20190902_1701'),
        ('kpermissions', '0002_remove_kpermissionsentity_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpermissionsentity',
            name='sub_type',
            field=models.ForeignKey(default=None, on_delete=1, to='sub_type.SubType'),
        ),
    ]
