# Generated by Django 2.2.3 on 2019-09-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryentity',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='repositoryentity',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='repositoryentity',
            name='repository_type',
            field=models.IntegerField(),
        ),
    ]
