# Generated by Django 2.2.3 on 2019-09-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20190912_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryentity',
            name='parent_id',
            field=models.UUIDField(blank=True),
        ),
    ]
