# Generated by Django 2.2.3 on 2019-09-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20190912_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryentity',
            name='desc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
