# Generated by Django 2.2.3 on 2019-09-26 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kpermissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KroleEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20)),
                ('is_active', models.IntegerField()),
                ('desc', models.CharField(blank=True, max_length=20)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
                ('update_date', models.DateTimeField(verbose_name='date modified')),
            ],
            options={
                'db_table': 'k_role',
            },
        ),
        migrations.CreateModel(
            name='Krole2KpermissionsEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
                ('update_date', models.DateTimeField(verbose_name='date modified')),
                ('permission', models.ForeignKey(on_delete=1, to='kpermissions.KpermissionsEntity')),
                ('role', models.ForeignKey(on_delete=1, to='krole.KroleEntity')),
            ],
            options={
                'db_table': 'k_role2permissions',
            },
        ),
    ]
