# Generated by Django 2.2.3 on 2019-09-26 13:47

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('krole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser2RoleEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
                ('update_date', models.DateTimeField(verbose_name='date modified')),
                ('role', models.ForeignKey(on_delete=1, to='krole.KroleEntity')),
                ('user', models.ForeignKey(on_delete=1, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authUser2role',
            },
        ),
    ]
