# Generated by Django 2.2.3 on 2019-09-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krole', '0002_authuser2roleentity'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authuser2roleentity',
            table='k_authUser2role',
        ),
    ]
