# Generated by Django 2.2.3 on 2019-09-05 02:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repository', '0002_auto_20190905_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebServiceEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webservice_name', models.CharField(max_length=50)),
                ('webservice_desc', models.TextField(blank=True)),
                ('webservice_html', models.TextField(blank=True)),
                ('webservice_res_desc', models.TextField(blank=True)),
                ('desc', models.CharField(blank=True, max_length=20)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
                ('update_date', models.DateTimeField(verbose_name='date modified')),
                ('parent', models.ForeignKey(on_delete=1, to='repository.RepositoryEntity')),
            ],
            options={
                'db_table': 'web_service',
            },
        ),
    ]
