# Generated by Django 2.2.3 on 2019-09-05 03:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebServiceParam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('param_name', models.CharField(max_length=50)),
                ('param_value', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
                ('update_date', models.DateTimeField(verbose_name='date modified')),
                ('is_active', models.IntegerField(default=1)),
                ('webservice', models.ForeignKey(on_delete=1, to='webservice.WebServiceEntity')),
            ],
        ),
    ]
