# Generated by Django 2.2.3 on 2019-09-05 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0002_webserviceparam'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='webserviceparam',
            table='web_service_param',
        ),
    ]
