# Generated by Django 2.2.3 on 2019-09-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0003_auto_20190905_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='webserviceentity',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
