# Generated by Django 2.2.3 on 2019-08-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtype',
            name='parent_id',
            field=models.ForeignKey(on_delete=1, to='top_type.TopType'),
        ),
    ]
