# Generated by Django 2.2.3 on 2019-08-30 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_type', '0002_auto_20190830_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtype',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
