# Generated by Django 2.2.3 on 2019-09-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_type', '0003_auto_20190830_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtype',
            name='type_url',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='subtype',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
