# Generated by Django 2.2.3 on 2019-09-18 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogInfoEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'db_table': 'log_info',
            },
        ),
    ]
